// Personal Values Card Sort — W.R. Miller, J. C'de Baca, D.B. Matthews,
// P.L. Wilbourne; University of New Mexico, 2001. Public domain.
export const VALUES = [
  { id: 1,  name: 'Acceptance',      blurb: 'to be accepted as I am' },
  { id: 2,  name: 'Accuracy',        blurb: 'to be accurate in my opinions and beliefs' },
  { id: 3,  name: 'Achievement',     blurb: 'to have important accomplishments' },
  { id: 4,  name: 'Adventure',       blurb: 'to have new and exciting experiences' },
  { id: 5,  name: 'Attractiveness',  blurb: 'to be physically attractive' },
  { id: 6,  name: 'Authority',       blurb: 'to be in charge of and responsible for others' },
  { id: 7,  name: 'Autonomy',        blurb: 'to be self-determined and independent' },
  { id: 8,  name: 'Beauty',          blurb: 'to appreciate beauty around me' },
  { id: 9,  name: 'Caring',          blurb: 'to take care of others' },
  { id: 10, name: 'Challenge',       blurb: 'to take on difficult tasks and problems' },
  { id: 11, name: 'Change',          blurb: 'to have a life full of change and variety' },
  { id: 12, name: 'Comfort',         blurb: 'to have a pleasant and comfortable life' },
  { id: 13, name: 'Commitment',      blurb: 'to make enduring, meaningful commitments' },
  { id: 14, name: 'Compassion',      blurb: 'to feel and act on concern for others' },
  { id: 15, name: 'Contribution',    blurb: 'to make a lasting contribution in the world' },
  { id: 16, name: 'Cooperation',     blurb: 'to work collaboratively with others' },
  { id: 17, name: 'Courtesy',        blurb: 'to be considerate and polite toward others' },
  { id: 18, name: 'Creativity',      blurb: 'to have new and original ideas' },
  { id: 19, name: 'Dependability',   blurb: 'to be reliable and trustworthy' },
  { id: 20, name: 'Duty',            blurb: 'to carry out my duties and obligations' },
  { id: 21, name: 'Ecology',         blurb: 'to live in harmony with the environment' },
  { id: 22, name: 'Excitement',      blurb: 'to have a life full of thrills and stimulation' },
  { id: 23, name: 'Faithfulness',    blurb: 'to be loyal and true in relationships' },
  { id: 24, name: 'Fame',            blurb: 'to be known and recognized' },
  { id: 25, name: 'Family',          blurb: 'to have a happy, loving family' },
  { id: 26, name: 'Fitness',         blurb: 'to be physically fit and strong' },
  { id: 27, name: 'Flexibility',     blurb: 'to adjust to new circumstances easily' },
  { id: 28, name: 'Forgiveness',     blurb: 'to be forgiving of others' },
  { id: 29, name: 'Friendship',      blurb: 'to have close, supportive friends' },
  { id: 30, name: 'Fun',             blurb: 'to play and have fun' },
  { id: 31, name: 'Generosity',      blurb: 'to give what I have to others' },
  { id: 32, name: 'Genuineness',     blurb: 'to act in a manner that is true to who I am' },
  { id: 33, name: 'God’s will',      blurb: 'to seek and obey the will of God' },
  { id: 34, name: 'Growth',          blurb: 'to keep changing and growing' },
  { id: 35, name: 'Health',          blurb: 'to be physically well and healthy' },
  { id: 36, name: 'Helpfulness',     blurb: 'to be helpful to others' },
  { id: 37, name: 'Honesty',         blurb: 'to be honest and truthful' },
  { id: 38, name: 'Hope',            blurb: 'to maintain a positive and optimistic outlook' },
  { id: 39, name: 'Humility',        blurb: 'to be modest and unassuming' },
  { id: 40, name: 'Humor',           blurb: 'to see the humorous side of myself and the world' },
  { id: 41, name: 'Independence',    blurb: 'to be free from dependence on others' },
  { id: 42, name: 'Industry',        blurb: 'to work hard and well at my life tasks' },
  { id: 43, name: 'Inner peace',     blurb: 'to experience personal peace' },
  { id: 44, name: 'Intimacy',        blurb: 'to share my innermost experiences with others' },
  { id: 45, name: 'Justice',         blurb: 'to promote fair and equal treatment for all' },
  { id: 46, name: 'Knowledge',       blurb: 'to learn and contribute valuable knowledge' },
  { id: 47, name: 'Leisure',         blurb: 'to take time to relax and enjoy' },
  { id: 48, name: 'Loved',           blurb: 'to be loved by those close to me' },
  { id: 49, name: 'Loving',          blurb: 'to give love to others' },
  { id: 50, name: 'Mastery',         blurb: 'to be competent in my everyday activities' },
  { id: 51, name: 'Mindfulness',     blurb: 'to live conscious and mindful of the present moment' },
  { id: 52, name: 'Moderation',      blurb: 'to avoid excesses and find a middle ground' },
  { id: 53, name: 'Monogamy',        blurb: 'to have one close, loving relationship' },
  { id: 54, name: 'Non-conformity',  blurb: 'to question and challenge authority and norms' },
  { id: 55, name: 'Nurturance',      blurb: 'to take care of and nurture others' },
  { id: 56, name: 'Openness',        blurb: 'to be open to new experiences, ideas, and options' },
  { id: 57, name: 'Order',           blurb: 'to have a life that is well-ordered and organized' },
  { id: 58, name: 'Passion',         blurb: 'to have deep feelings about ideas, activities, or people' },
  { id: 59, name: 'Pleasure',        blurb: 'to feel good' },
  { id: 60, name: 'Popularity',      blurb: 'to be well-liked by many people' },
  { id: 61, name: 'Power',           blurb: 'to have control over others' },
  { id: 62, name: 'Purpose',         blurb: 'to have meaning and direction in my life' },
  { id: 63, name: 'Rationality',     blurb: 'to be guided by reason and logic' },
  { id: 64, name: 'Realism',         blurb: 'to see and act realistically and practically' },
  { id: 65, name: 'Responsibility',  blurb: 'to make and carry out responsible decisions' },
  { id: 66, name: 'Risk',            blurb: 'to take risks and chances' },
  { id: 67, name: 'Romance',         blurb: 'to have intense, exciting love in my life' },
  { id: 68, name: 'Self-acceptance', blurb: 'to accept myself as I am' },
  { id: 69, name: 'Safety',          blurb: 'to be safe and secure' },
  { id: 70, name: 'Self-control',    blurb: 'to be disciplined in my own actions' },
  { id: 71, name: 'Self-esteem',     blurb: 'to feel good about myself' },
  { id: 72, name: 'Self-knowledge',  blurb: 'to have a deep and honest understanding of myself' },
  { id: 73, name: 'Service',         blurb: 'to be of service to others' },
  { id: 74, name: 'Sexuality',       blurb: 'to have an active and satisfying sex life' },
  { id: 75, name: 'Simplicity',      blurb: 'to live life simply, with minimal needs' },
  { id: 76, name: 'Solitude',        blurb: 'to have time and space where I can be apart from others' },
  { id: 77, name: 'Spirituality',    blurb: 'to grow and mature spiritually' },
  { id: 78, name: 'Stability',       blurb: 'to have a life that stays fairly consistent' },
  { id: 79, name: 'Tolerance',       blurb: 'to accept and respect those who differ from me' },
  { id: 80, name: 'Tradition',       blurb: 'to follow respected patterns of the past' },
  { id: 81, name: 'Virtue',          blurb: 'to live a morally pure and excellent life' },
  { id: 82, name: 'Wealth',          blurb: 'to have plenty of money' },
  { id: 83, name: 'World peace',     blurb: 'to work to promote peace in the world' },
];
